/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/sitemap.xml' | '/api/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/sitemap.xml' | '/api/transcribe'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/api/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
